metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "fc2ec5005f3c388b0f09be48e71f14b17635423ef54ae24555660be13caf879f"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "xPwtOuVOfjXc5kGfec+RVFBZYNNYrTR2TJb27KR/2so="
metrics_token = "ZTxHGwuHv5be0QSNohD4TeZeGsltBNtVgqwhYL9E2z4="
